title: Airgo Atlas-AI
description: FEM plugin suite for handling SFRP simulations

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
